version: '3'
services:
  aiogrambot:
    restart: unless-stopped
    build: .
    depends_on:
      - my_redis
  my_redis:
    image: redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
